#!/bin/bash

#script wordsel takes two arguments, numbers m  n
#reads line of words input from stdin and stores them in array
#outputs the words within range of two arguments  m to n
#postion in array is 0 based


while read -a words
do
  for ((i=$1; i <= $2; i++))
  do
    echo -n "${words[${i}]} "
  done 
  echo ""
done

