#!/bin/bash

#takes argument list and shuffles/rearranges the members
#cuts argument list in half, 
#both halves are equal in number if even # args given,
#otherwise second half greater than first by 1, if odd # args
# last element of arg list returned first
# followed by alternate sequence of successive elements
# from first and second halves.
# eg.  arg list of ->   a b c d e
# would return ->     e a c b d

if (( $# > 0 ))
then
  mid=$((${#}/2))
  last=$#
  echo ${!last}

  for ((i=1; i<=${mid}; i++))
  do
    echo "${!i}    # first piece"
    j=$((${mid}+${i}))
    if (( i != ${mid} || ${#}%2 != 0 ))
    then
      echo "${!j}"
    fi
  done
  
else
  echo "No arguments given"
fi

