#!/bin/bash

# script whyq takes an argument and analyzes it
# for need to be quoted if it
#     - is empty string
#     - contains white space
#     - contains globchars of ?!*{}[]
# otherwise it is normal
# 
# outputs the argument enclosed in brackets and 
# string of analysis

sout="[${*}]"
special=0

if [[ $1 == '' ]]
then
  echo "$sout is the empty string"
else
  if [[ $1 =~ " " ]]
  then
    echo "$sout contains whitespace"
    special=1
  fi
  if [[ $1 =~ ['?!*{}'] ]] || [[ $1 =~ ']' ]] || [[ $1 =~ '[' ]]   #had to do or's to match single [ or ], to work
  then
    echo "$sout contains globchars"
    special=1
  fi
  if (( $special == 0 ))
  then
    echo "$sout is not special"
  fi
fi
